version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: remove pre-build packages && install-dependencies
          command: yarn remove ngx-swing
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: build
          command: yarn ng -- build --prod --aot --project="ngx-swing" --no-progress
      - run:
          name: test
          command: yarn test -- --single-run --project="ngx-swing" --no-progress
      - store_artifacts:
          path: test-results.xml
          prefix: tests